### ISSUE TITLE
Fix incorrect parsing in certain circumstances

### ISSUE THREAD

**Issue by andornaut** [zeke/markdown-index#2]
## Test Case

```
cd $(mktemp -d)
mkdir t
echo '# a

## b

- [b](b)
XXX

XXX

## NOT FOUND

XXX

XXX

## ALSO NOT FOUND

XXX

XXX' | tr X '`' > t/a.md

npm install -q markdown-index >/dev/null 2>&1
./node_modules/markdown-index/index.js t
```
## Actual output

```
### [A](t/a.md)

* [b](t/a.md#b)
```
## Expected output

```
### [A](t/a.md)

* [b](t/a.md#b)
* [NOT FOUND](t/a.md#not-found)
* [ALSO NOT FOUND](t/a.md#also-not-found)
```
## Observation

Removing the following line and re-running the test case produces the expected output:

```
- [b](b)
```

**Comment by zeke** [comment]
Hi @andornaut. Thanks for reporting. I'm guessing this is an issue in the `marked-toc` package, which appears to be [deprecated in favor of markdown-toc](https://github.com/jonschlinkert/markdown-toc). I would happily accept a PR that switches out that dependency.
